{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"DetectSign.ipynb","provenance":[],"authorship_tag":"ABX9TyP+ScrGhXxOemI8hfBsVS/0"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"id":"QkOi6DwA0Gdb","executionInfo":{"status":"ok","timestamp":1604821865655,"user_tz":-420,"elapsed":796,"user":{"displayName":"Khánh Đào Minh","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiRHc11TB8nYIxID6505-CWW68otCE8nspNa6a7hw=s64","userId":"14493180791010014004"}},"outputId":"113f1971-7bf6-4b47-97ed-bbe72b871181","colab":{"base_uri":"https://localhost:8080/"}},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"YxGKZsMo0Kd1","executionInfo":{"status":"error","timestamp":1604821991724,"user_tz":-420,"elapsed":846,"user":{"displayName":"Khánh Đào Minh","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiRHc11TB8nYIxID6505-CWW68otCE8nspNa6a7hw=s64","userId":"14493180791010014004"}},"outputId":"accc1e6c-94d4-47d4-af9c-6631c79e2a35","colab":{"base_uri":"https://localhost:8080/"}},"source":["%cd /content\n","!unzip /content/drive/'My Drive'/Yolo/darknet.zip\n","%cd /content/darknet"],"execution_count":17,"outputs":[{"output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"],"name":"stderr"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-17-d45359f6e633>\", line 1, in <module>\n","    get_ipython().magic('cd /content')\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2160, in magic\n","    return self.run_line_magic(magic_name, magic_arg_s)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 2081, in run_line_magic\n","    result = fn(*args,**kwargs)\n","  File \"<decorator-gen-91>\", line 2, in cd\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py\", line 188, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/magics/osm.py\", line 288, in cd\n","    oldcwd = py3compat.getcwd()\n","FileNotFoundError: [Errno 2] No such file or directory\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py\", line 1823, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.6/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.6/inspect.py\", line 725, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.6/inspect.py\", line 709, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.6/posixpath.py\", line 383, in abspath\n","    cwd = os.getcwd()\n","FileNotFoundError: [Errno 2] No such file or directory\n"],"name":"stdout"},{"output_type":"error","ename":"FileNotFoundError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"]}]},{"cell_type":"code","metadata":{"id":"QvmbHnJt0Tga","executionInfo":{"status":"ok","timestamp":1604821826530,"user_tz":-420,"elapsed":20,"user":{"displayName":"Khánh Đào Minh","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiRHc11TB8nYIxID6505-CWW68otCE8nspNa6a7hw=s64","userId":"14493180791010014004"}},"outputId":"90e4cf72-06f3-4e2e-91f1-2c30bed9b612","colab":{"base_uri":"https://localhost:8080/"}},"source":["!make\n","!chmod +x ./darknet"],"execution_count":null,"outputs":[{"output_type":"stream","text":["make: Nothing to be done for 'all'.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"r8MZkssS0Vim"},"source":["!rm /content/darknet/backup -r\n","!ln -s /content/drive/'My Drive'/Yolo/backup /content/darknet"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"AhVrl7AY0XSx"},"source":["%cd /content/darknet\n","!./darknet detector train yolo.data cfg/yolov3.cfg darknet53.conv.74"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"0jMN_1nZ083i"},"source":[""],"execution_count":null,"outputs":[]}]}